local highlights = {
	Bold = { style = "bold" },
	Boolean = { fg = C.red },
	Character = { fg = C.gold },
	ColorColumn = { bg = C.off_black },
	Comment = { fg = C.dark_grey, style = "italic" },
	Conceal = { fg = C.off_white },
	Conditional = { fg = C.red },
	Constant = { fg = C.cyan },
	CursorColumn = { bg = C.off_black },
	Cursor = { fg = C.off_black, bg = C.red },
	CursorIM = { fg = C.off_black, bg = C.red },
	CursorLine = { bg = C.off_black },
	CursorLineNr = { fg = C.dark_grey, style = "bold" },
	Debug = { fg = C.red },
  Define = { fg = C.red },
	Delimiter = { fg = C.off_white },
	DiffAdd = { fg = C.off_black, bg = C.green },
	DiffChange = { fg = C.off_black, bg = C.teal2, style = "underline" },
	DiffDelete = { fg = C.off_black, bg = C.red },
	Directory = { fg = C.off_white },
	EndOfBuffer = { fg = C.off_black },
	Error = { fg = C.off_black, bg = C.red, style = "bold" },
	ErrorMsg = { fg = C.off_black, bg = C.red, style = "bold" },
	Exception = { fg = C.red },
	FloatBorder = { fg = C.red, bg = C.off_black },
	Float = { fg = C.red },
	FoldColumn = { fg = C.off_white, bg = C.off_black },
	Folded = { fg = C.off_white, bg = C.off_black },
	Function = { fg = C.red },
	Identifier = { fg = C.off_white },
	Ignore = { fg = C.off_black, bg = C.red, style = "bold" },
	Include = { fg = C.red },
	IncSearch = { fg = C.off_white, bg = C.dark_grey },
	Italic = { style = "italic" },
	Keyword = { fg = C.off_black, bg = C.red },
	Label = { fg = C.off_white },
	lCursor = { fg = C.off_black, bg = C.red },
	LineNr = { fg = C.dark_grey },
	Macro = { fg = C.off_white },
	MatchParenCur = { fg = C.off_black, bg = C.red, style = "underline" },
	MatchParen = { fg = C.off_black, bg = C.red, style = "underline" },
	MatchWordCur = { style = "underline" },
	MatchWord = { fg = C.off_black, bg = C.red, style = "underline" },
	ModeMsg = { fg = C.off_white, bg = C.off_black },
	MoreMsg = { fg = C.off_white, bg = C.off_black },
	MsgArea = { fg = C.off_white, bg = Config.transparent_background and "NONE" or C.off_black },
	MsgSeparator = { fg = C.off_white, bg = C.off_black },
	NonText = { fg = C.off_black },
	Normal = { fg = C.off_white, bg = Config.transparent_background and "NONE" or C.off_black },
	NormalFloat = { bg = C.off_black },
	NormalNC = { fg = C.off_white, bg = Config.transparent_background and "NONE" or C.off_black },
	Number = { fg = C.off_white },
	Operator = { fg = C.off_white },
	Pmenu = { fg = C.off_white, bg = C.off_black },
	PmenuSbar = { bg = C.off_black },
	PmenuSel = { bg = C.off_black },
	PmenuThumb = { bg = C.red },
	PreCondit = { fg = C.red },
	PreProc = { fg = C.off_white },
	Question = { fg = C.red },
	QuickFixLine = { fg = C.off_black, bg = C.red },
	Repeat = { fg = C.red },
	Search = { fg = C.off_black, bg = C.red },
	SignColumn = { bg = C.off_black },
	SpecialChar = { fg = C.off_white },
	SpecialComment = { fg = C.dark_grey },
	Special = { fg = C.off_white },
	SpecialKey = { fg = C.gold, style = "bold" },
	SpellBad = { fg = C.red, style = "underline" },
	SpellCap = { fg = C.gold, style = "underline" },
	SpellLocal = { fg = C.dark_grey, style = "underline" },
	SpellRare = { fg = C.dark_grey, style = "underline" },
	Statement = { fg = C.red },
	StorageClass = { fg = C.red },
	String = { fg = C.gold },
	Structure = { fg = C.red },
	Substitute = { fg = C.off_white, bg = C.dark_grey },
	TabLine = { fg = C.off_white, bg = C.dark_grey },
	TabLineFill = { fg = C.off_black, bg = C.off_black },
	TabLineSel = { fg = C.off_white, bg = C.off_black },
	Tag = { fg = C.red },
	TermCursor = { fg = C.off_white, bg = C.dark_grey },
	TermCursorNC = { fg = C.off_white, bg = C.dark_grey },
	Title = { fg = C.off_white, style = "bold" },
	Todo = { fg = C.green, bg = C.bg_2, style = "bold" },
	Typedef = { fg = C.red },
	Type = { fg = C.red },
	Underlined = { style = "underline" },
	Variable = { fg = C.red },
	VertSplit = { fg = C.red, bg = C.off_black },
	Visual = { fg = C.red, bg = C.off_black },
	VisualNOS = { fg = C.red, bg = C.off_black },
	WarningMsg = { fg = C.off_black, bg = C.red },
	Whitespace = { fg = C.off_black },
	WildMenu = { fg = C.off_white, bg = C.dark_grey },
}
return highlights
