local lsp = {
	LspDiagnosticsDefaultError = { fg = C.red },
	LspDiagnosticsDefaultWarning = { fg = C.dark_gold },
	LspDiagnosticsDefaultInformation = { fg = C.gold },
	LspDiagnosticsDefaultInfo = { fg = C.gold },
	LspDiagnosticsDefaultHint = { fg = C.teal2 },
	LspDiagnosticsVirtualTextError = { fg = C.red },
	LspDiagnosticsVirtualTextWarning = { fg = C.gold },
	LspDiagnosticsVirtualTextInformation = { fg = C.dark_gold },
	LspDiagnosticsVirtualTextInfo = { fg = C.gold },
	LspDiagnosticsVirtualTextHint = { fg = C.teal2 },
	LspDiagnosticsFloatingError = { fg = C.red },
	LspDiagnosticsFloatingWarning = { fg = C.gold },
	LspDiagnosticsFloatingInformation = { fg = C.dark_gold },
	LspDiagnosticsFloatingInfo = { fg = C.dark_gold },
	LspDiagnosticsFloatingHint = { fg = C.teal2 },
	DiagnosticSignError = { fg = C.red },
	DiagnosticSignWarning = { fg = C.gold },
	DiagnosticSignInformation = { fg = C.dark_gold },
	DiagnosticSignInfo = { fg = C.dark_gold },
	DiagnosticSignHint = { fg = C.teal2 },
	LspDiagnosticsSignError = { fg = C.red },
	LspDiagnosticsSignWarning = { fg = C.gold },
	LspDiagnosticsSignInformation = { fg = C.dark_gold },
	LspDiagnosticsSignInfo = { fg = C.dark_gold },
	LspDiagnosticsSignHint = { fg = C.teal2 },
	LspDiagnosticsError = { fg = C.red },
	LspDiagnosticsWarning = { fg = C.gold },
	LspDiagnosticsInformation = { fg = C.dark_gold },
	LspDiagnosticsInfo = { fg = C.dark_gold },
	LspDiagnosticsHint = { fg = C.teal2 },
	LspDiagnosticsUnderlineError = { style = "underline" },
	LspDiagnosticsUnderlineWarning = { style = "underline" },
	LspDiagnosticsUnderlineInformation = { style = "underline" },
	LspDiagnosticsUnderlineInfo = { style = "underline" },
	LspDiagnosticsUnderlineHint = { style = "underline" },
	LspReferenceRead = { bg = C.black },
	LspReferenceText = { bg = C.black },
	LspReferenceWrite = { bg = C.black },
}

return lsp
