local misc = {
    diffAdded = { fg = C.green },
    diffRemoved = { fg = C.red },
    diffFileId = { fg = C.off_white, style = "bold,reverse" },
    diffFile = { fg = C.black },
    diffNewFile = { fg = C.green },
    diffOldFile = { fg = C.red },
    debugPc = { bg = C.red },
    debugBreakpoint = { fg = C.red, style = "reverse" },
    CodiVirtualText = { fg = C.teal },
    SniprunVirtualTextOk = { fg = C.teal },
    SniprunFloatingWinOk = { fg = C.teal },
    SniprunVirtualTextErr = { fg = C.red },
    SniprunFloatingWinErr = { fg = C.red },
    CompeDocumentation = { bg = C.black },
    DapBreakpoint = { fg = C.red },
    xmlTag = { fg = C.red },
    xmlTagName = { fg = C.red },
    xmlEndTag = { fg = C.red },
    yamlPlainScalar = { fg = C.red },
    yamlTSField = { fg = C.red },
    luaFunc = { fg = C.red },
    luaFunction = { fg = C.red },
    htmlH1 = { fg = C.off_white },
    htmlH2 = { fg = C.off_white },
    htmlH3 = { fg = C.off_white },
    htmlH4 = { fg = C.off_white },
    htmlH5 = { fg = C.off_white },
    htmlH6 = { fg = C.off_white },
    htmlHead = { fg = C.off_white },
    htmlTitle = { fg = C.off_white },
    htmlArg = { fg = C.red },
    htmlTag = { fg = C.red },
    htmlTagN = { fg = C.red },
    htmlTagName = { fg = C.red },
    htmlComment = { fg = C.dark_grey },
    htmlLink = { fg = C.cyan, style = "underline" },
    cssBraces = { fg = C.off_white },
    cssInclude = { fg = C.red },
    cssTagName = { fg = C.red },
    cssClassName = { fg = C.red },
    cssPseudoClass = { fg = C.red },
    cssPseudoClassId = { fg = C.red },
    cssPseudoClassLang = { fg = C.red },
    cssIdentifier = { fg = C.red },
    cssProp = { fg = C.teal },
    cssDefinition = { fg = C.dark_grey },
    cssAttr = { fg = C.red },
    cssAttrRegion = { fg = C.red },
    cssColor = { fg = C.red },
    cssFunction = { fg = C.red },
    cssFunctionName = { fg = C.red },
    cssVendor = { fg = C.red },
    cssValueNumber = { fg = C.off_white },
    cssValueLength = { fg = C.off_white },
    cssUnitDecorators = { fg = C.off_white },
    cssStyle = { fg = C.red },
    cssImportant = { fg = C.red },
    jsonKeyword = { fg = C.red },
    yamlBlockMappingKey = { fg = C.red },
  }
  
  return misc
  
  