local treesitter = {
	TSComment = { fg = C.dark_grey },
	TSAnnotation = { fg = C.dark_grey },
	TSAttribute = { fg = C.red },
	TSConstructor = { fg = C.red },
	TSType = { fg = C.red },
	TSTypeBuiltin = { fg = C.red },
	TSConditional = { fg = C.red },
	TSException = { fg = C.red },
	TSInclude = { fg = C.red },
	TSKeywordReturn = { fg = C.red },
	TSKeyword = { fg = C.red },
	TSKeywordFunction = { fg = C.red },
	TSLabel = { fg = C.red },
	TSNamespace = { fg = C.cyan },
	TSRepeat = { fg = C.red },
	TSConstant = { fg = C.red },
	TSConstBuiltin = { fg = C.red },
	TSFloat = { fg = C.red },
	TSNumber = { fg = C.red },
	TSBoolean = { fg = C.red },
	TSCharacter = { fg = C.dp },
	TSError = { fg = C.red },
	TSFunction = { fg = C.red },
	TSFuncBuiltin = { fg = C.red },
	TSMethod = { fg = C.red },
	TSConstMacro = { fg = C.red },
	TSFuncMacro = { fg = C.red },
	TSVariable = { fg = C.red },
	TSVariableBuiltin = { fg = C.red },
	TSProperty = { fg = C.red },
	TSOperator = { fg = C.red },
	TSField = { fg = C.red },
	TSParameter = { fg = C.gold },
	TSParameterReference = { fg = C.gold },
	TSSymbol = { fg = C.red },
	TSText = { fg = C.off_white },
	TSPunctDelimiter = { fg = C.dark_grey },
	TSTagDelimiter = { fg = C.red },
	TSTagAttribute = { fg = C.red },
	TSPunctBracket = { fg = C.red },
	TSPunctSpecial = { fg = C.red },
	TSString = { fg = C.red },
	TSStringRegex = { fg = C.red },
	TSTag = { fg = C.red },
	TSEmphasis = { style = "italic" },
	TSUnderline = { style = "underline" },
	TSTitle = { fg = C.off_white },
	TSLiteral = { fg = C.green },
	TSURI = { fg = C.cyan, style = "underline" },
	TSKeywordOperator = { fg = C.red },
	TSStructure = { fg = C.red },
	TSStrong = { fg = C.reed, style = "bold" },
	TSQueryLinterError = { fg = C.red },
	TreesitterContext = { bg = C.dark_grey },
}

return treesitter
